#  docker-compose -f docker-compose.yml config check validate config
version: "3.7"
services:
  OkanizeBackend:
    build:
      context: .
      dockerfile: Dockerfile
    image: "okanizebackend:v1"
    container_name: OkanizeBackend
    working_dir: /app
    restart: "always"
    ports:
      - "4000:4000"
    expose:
      - "4000"
    labels:
      com.docker.compose.project: "OkanizeBackend"
      virtual.host: "okanizeapi.shopsthai.com"
      virtual.tls-email: limweb@hotmail.com
      virtual.port: "4000"
    environment:
      - DATABASE_HOST=dbpostgresql
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=o8&7Ez#SeozKLXFr
      - DATABASE_NAME=okanize_db
      - PORT=4000
      - LINE_CHANNEL_ID=2007080121
      - LINE_CHANNEL_ACCESS_TOKEN='9XcUFev0feiP75e7DeZCajUWZQBYg4tkiEmMkdgFHC0v2WkzQHHb3HkR8HK9TNA6skfWQnJFPVi3yLuu8ULe0ySwbg6bmAZSedxKzTE3qUFuO6imsuG2x7GRPbJrDydbs1t1fCEbrjsrIjUUzqH34gdB04t89/1O/w1cDnyilFU='

networks:
  default:
    external: true
    name: proxy-network
